const fullGymItems = [
  { id: "dumbbells", label: "Dumbbells" },
  { id: "barbells", label: "Barbells" },
  { id: "cable-crossover-machine", label: "Cable Crossover Machine" },
  { id: "bench-press", label: "Bench Press" },
  { id: "adjustable-bench", label: "Adjustable Bench" },
  { id: "lat-pull-down-machine", label: "Lat Pull Down Machine" },
  { id: "ab-roller", label: "Ab Roller" },
  { id: "leg-extension-machine", label: "Leg Extension Machine" },
  { id: "treadmill", label: "Treadmill" },
  { id: "spin-bike", label: "Spin Bike" },
  { id: "aerobic-steps", label: "Aerobic Steps" },
  { id: "seated-row-machine", label: "Seated Row Machine" },
  { id: "kettlebells", label: "Kettlebells" },
  { id: "exercise-mat", label: "Exercise Mat" },
  { id: "leg-press", label: "Leg Press" },
  { id: "smith-machine", label: "Smith Machine" },
  { id: "power-rack", label: "Power Rack" },
  { id: "chest-press-machine", label: "Chest Press Machine" },
  { id: "leg-curl-machine", label: "Leg Curl Machine" },
  { id: "calf-raise-machine", label: "Calf Raise Machine" },
  { id: "preacher-curl-bench", label: "Preacher Curl Bench" },
  { id: "tricep-dip-machine", label: "Tricep Dip Machine" },
  { id: "shoulder-press-machine", label: "Shoulder Press Machine" },
  { id: "rowing-machine", label: "Rowing Machine" },
  { id: "elliptical-trainer", label: "Elliptical Trainer" },
  { id: "stair-climber", label: "Stair Climber" },
  { id: "battle-ropes", label: "Battle Ropes" },
  { id: "medicine-balls", label: "Medicine Balls" },
  { id: "bosu-ball", label: "BOSU Ball" },
  { id: "trx-suspension-trainer", label: "TRX Suspension Trainer" },
  { id: "sled-push", label: "Sled Push" },
  { id: "pull-up-bar", label: "Pull-Up Bar" },
  { id: "hyperextension-bench", label: "Hyperextension Bench" },
  { id: "glute-ham-developer", label: "Glute-Ham Developer" },
  { id: "adjustable-dumbbells", label: "Adjustable Dumbbells" },
  { id: "plyo-boxes", label: "Plyo Boxes" },
  { id: "resistance-bands", label: "Resistance Bands" },
  { id: "foam-roller", label: "Foam Roller" },
  { id: "punching-bag", label: "Punching Bag" },
  { id: "speed-bag", label: "Speed Bag" },
  { id: "vertical-knee-raise", label: "Vertical Knee Raise" },
  { id: "ab-crunch-machine", label: "Ab Crunch Machine" },
  { id: "vibration-plate", label: "Vibration Plate" }
];

export default fullGymItems;
